### ISSUE TITLE
Workspace file operations missing from trait

### ISSUE THREAD

**Issue by samscott89** [silvanshade/lspower#14]
Hi, there are a few methods missing from the `LanguageServer` trait. The ones I noticed were for file renaming/deletion.

If it's helpful, it looks like these were added in `tower-lsp` in this commit: https://github.com/ebkalderon/tower-lsp/commit/ef992773a32a2186a29d9bf6eb3b3fddc9460642

**Comment by silvanshade** [comment]
Thanks for letting me know. I'll try to make an update for this soon.
