### ISSUE TITLE
Is there any way to receive a custom request from client？

### ISSUE THREAD

**Issue by IWANABETHATGUY** [silvanshade/lspower#9]
I want to receive a custom request send from vscode client, but found the following logging:
```
[2021-05-13T13:54:18Z ERROR lspower] Got a tjs-postfix.ast-preview request, but LanguageServer::request_else is not implemented

```

**Comment by silvanshade** [comment]
Yes, what you need to do is provide an implementation for the `LanguageServer::request_else` method as you would for the other standard request handlers. The `LanguageServer::request_else` provides you with the method name and params that you process as needed for your custom messages.

See: https://github.com/silvanshade/lspower/blob/bcf2358518e54798aa70a08dd662a4152c1e927d/src/lib.rs#L756.

**Comment by IWANABETHATGUY** [comment]
Thanks!
